# Bagging

In [1]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
base_classifier = DecisionTreeClassifier()

In [4]:
bagging_classifier = BaggingClassifier(base_classifier, n_estimators=10, random_state=42)
bagging_classifier.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), random_state=42)

In [5]:
y_pred = bagging_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

# Boosting

In [6]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [7]:
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
base_classifier = DecisionTreeClassifier(max_depth=1)

In [9]:
adaboost_classifier = AdaBoostClassifier(
    base_classifier, n_estimators=50, learning_rate=1.0, random_state=42
)
adaboost_classifier.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   random_state=42)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

# Stacking

In [11]:
%pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (2.4.2)
Requirement already satisfied: pandas>=2.3.3 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (3.0.1)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\indiranivas_s\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\indiranivas_s\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\indiranivas_s\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\indiranivas_s\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 9.7 MB/s  0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.24.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.classifier import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score

In [13]:
df = pd.read_csv('heart.csv')    
                 
X = df.drop('target', axis = 1)
y = df['target']

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
sc = StandardScaler()  

var_transform = ['thalach', 'age', 'trestbps', 'oldpeak', 'chol']
X_train[var_transform] = sc.fit_transform(X_train[var_transform])   
X_test[var_transform] = sc.transform(X_test[var_transform])           

X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,-1.356798,1,1,-0.616856,0.914034,0,1,0.532781,0,-0.920864,2,0,2
202,0.385086,1,0,1.169491,0.439527,0,0,-1.753582,1,-0.193787,2,0,3
196,-0.921327,1,2,1.169491,-0.300704,0,1,-0.139679,0,2.350982,1,0,2
75,0.058483,0,1,0.276318,0.059921,0,0,0.487950,0,0.351521,1,0,2
176,0.602822,1,0,-0.795490,-0.319684,1,1,0.443119,1,0.351521,2,2,3

In [16]:
KNC = KNeighborsClassifier()   
NB = GaussianNB()

In [17]:
model_kNeighborsClassifier = KNC.fit(X_train, y_train)  
pred_knc = model_kNeighborsClassifier.predict(X_test)

acc_knc = accuracy_score(y_test, pred_knc)  
print('Accuracy Score of KNeighbors Classifier:', acc_knc * 100)

Accuracy Score of KNeighbors Classifier: 86.88524590163934

In [18]:
model_NaiveBayes = NB.fit(X_train, y_train)
pred_nb = model_NaiveBayes.predict(X_test)

acc_nb = accuracy_score(y_test, pred_nb)
print('Accuracy of Naive Bayes Classifier:', acc_nb * 100)

Accuracy of Naive Bayes Classifier: 86.88524590163934

In [21]:
base_learners = [
    KNeighborsClassifier(),
    GaussianNB()
]
meta_model = LogisticRegression()

stacking_model = StackingClassifier(classifiers=base_learners, meta_classifier=meta_model, use_probas=True)

In [20]:
model_stack = stacking_model.fit(X_train, y_train)   
pred_stack = model_stack.predict(X_test)

acc_stack = accuracy_score(y_test, pred_stack)
print('Accuracy Score of Stacked Model:', acc_stack * 100)

Accuracy Score of Stacked Model: 88.52459016393442